### ISSUE TITLE
Roadmap of v1.2.0

### ISSUE THREAD

**Issue by AaronPB** [AaronPB/force_platform#20]
The GUI update

### Config flexibility

- [x] Simplify `settings` config section.
- [x] Remove unused `settings`.
- [x] Remove fixed sensor groups sections.
- [x] Add `sensors` config section to list all sensors to be used.
- [x] Add `sensor_groups` config section where all groups are defined.
- [x] Add calibration sensors under a `sensor_calibration` section.

### New graphs

Related issues: #16 

- [x] Data preview.
- [x] Individual sensor graphs.
- [x] Specific group graphs for platforms: `Forces`, `COP`.
- [x] Add COP results to figure layout.
- [x] Add `NavigationToolbar` to figures.
- [x] Add markers and proper color set.

### Results settings

Related issues: #17 

- [x] Data limits.
- [x] Butterworth filter.
- [x] Save modified results.

### GUI redesign

- [x] Tab updates.
- [x] New design for sensor groups and status.
- [x] New layout for results settings.
- [x] New interface for individual sensor figures.
- [x] New interface for platform figures.
- [x] New calibration interface.

### Class refactors

- [x] Simplification of `Sensor` and `SensorGroup` handler methods and sensor type with new `SType`, `SGType` enums.
- [x] `DataManager` internal management with pandas dataframes.
- [x] `SensorManager` flexible sensor loader, instead of fixed groups.
- [x] Avoid `FileManager` to override initial name value, only update file suffix.
- [x] Update calibration process with those refactors, adding sensor selector.

### Tests

- [x] Include a test button to import a pre-recorded test with all sensor and sensor group types, to check results management and graphs.
- Update tests:
  - [x] `test_manager_config`.
  - [x] `test_manager_file`.
  - [x] `test_sensor`.
  - [x] `test_sensorgroup`.
