### ISSUE TITLE
Roadmap of v1.3.0

### ISSUE THREAD

**Issue by AaronPB** [AaronPB/force_platform#23]
**Work in progress. Objectives may change**

New external sensors and platform calibration process

### New `SENSOR_CAMERA` sensor type

- [x] Build new camera driver with OpenCV.
- [x] Define `SENSOR_CAMERA` params in `config.yaml`.
- [x] Create thread to handle camera recordings.
- [x] Create export functions to save video files in test folder.

### Platform calibration

- [x] Modify `sensors_calibration.platform_reference` config param to a list of 3 `SENSOR_LOADCEL` sensors.
- [x] Update platform reference sensor load in `SensorManager` class.

### Github workflows

- [x] New workflow to check python format with [Black](https://black.readthedocs.io/en/stable/integrations/github_actions.html)

### Project requirements

- [x] Update `requirements.txt` with new python modules (opencv and dependencies)
- [x] Update `requirements-dev.txt` also with Black formatter.
