### ISSUE TITLE
General checklist for version 1.0

### ISSUE THREAD

**Issue by AaronPB** [AaronPB/force_platform#5]
- [x] Fix matplots of main GUI showing up in new windows when the test is finished.
- [x] Make the result graph configurable in `config.yaml` file.
- [x] Fix test conditions status update when defining new folder paths.
- [x] Add external config load support.
- [x] Fix IMUs typeError from MRPT when getting observations.
- [x] Update `config.yaml` permalinks to latest commit in documentation.
- [x] Update Matlab scripts.
